### ISSUE TITLE
Unresolvable dependency in class Elasticsearch\Transport

### ISSUE THREAD

**Issue by tarasmedia** [Arslanoov/laravel-store#4]
**run composer install and got error**

Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException  : Unresolvable dependency resolving [Parameter #0 [ <required> $retries ]] in class Elasticsearch\Transport

  at D:\Apache24\html\vendor\laravel\framework\src\Illuminate\Container\Container.php:975
    971|     protected function unresolvablePrimitive(ReflectionParameter $parameter)
    972|     {
    973|         $message = "Unresolvable dependency resolving [$parameter] in class {$parameter->getDeclaringClass()->g
etName()}";
    974|
  > 975|         throw new BindingResolutionException($message);
    976|     }
    977|
    978|     /**
    979|      * Register a new resolving callback.

  Exception trace:

  1   Illuminate\Container\Container::unresolvablePrimitive(Object(ReflectionParameter))
      D:\Apache24\html\vendor\laravel\framework\src\Illuminate\Container\Container.php:913

  2   Illuminate\Container\Container::resolvePrimitive(Object(ReflectionParameter))
      D:\Apache24\html\vendor\laravel\framework\src\Illuminate\Container\Container.php:854

  Please use the argument -v to see more details.
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

**Comment by arturfse** [comment]
Fixed
